# This file was generated by liblab | https://liblab.com/

from ups_0auth_code import Ups0authCode, Environment
from ups_0auth_code.models import GenerateTokenRequest

sdk = Ups0authCode(
    username="YOUR_USERNAME",
    password="YOUR_PASSWORD",
    base_url=Environment.DEFAULT.value,
)

request_body = GenerateTokenRequest(
    grant_type="authorization_code", code="code", redirect_uri="redirect_uri"
)

result = sdk.token.generate_token(request_body=request_body)

print(result)
